# W03_0306 {#第三周}

## 案例討論
103年 0825日
五年的最後一天：
108年 0824

### 思考的點

請求退稅的法律性質爲何

五年的期間，其法律性質？

適用所得稅協定查核準則，其法律位階爲何？

適用之優先順序： 
- 納稅者權利保護法
- 稅捐稽徵
- 所得稅法
- 適用所得稅協定查核準則

現

    適用所得稅協定查核準則

    第 34 條
    1. 他方締約國之居住者取得屬所得稅法第八十八條規定扣繳範圍之所得，已依各類所得扣繳率標準課稅者，得由所得人或扣繳義務人自繳納之日起五年內，檢附第二十三條、第二十四條、第二十五條、第二十六條或第二十七條規定之證明文件及扣繳憑單，向原受理扣繳申報之稅捐稽徵機關辦理退還溢繳稅款，或按扣繳義務人所在地之轄區國稅局別，彙總其截至申請退稅前於各該局轄區內已扣繳之稅款及依所得稅協定應扣繳之稅款，計算其溢繳稅款之總數，向各該轄區國稅局（總局）彙總申請退還溢繳稅款。
    2. 他方締約國之居住者取得非屬所得稅法第八十八條規定扣繳範圍之所得，已依所得稅法規定申報納稅者，得自繳納之日起五年內，檢附第二十三條、第二十四條、第二十六條或第二十七條規定之證明文件、申報書及繳款書正本，向受理申報之稅捐稽徵機關辦理退還溢繳稅款。
    3. 前二項溢繳稅款得由所得人或扣繳義務人委由在中華民國境內居住之個人或有固定營業場所之營利事業辦理。

查

    適用所得稅協定查核準則

    第 1 條
    本準則依所得稅法第八十條第五項規定訂定之。

又

    所得稅法 第八十條第五項

    第 80 條

    1. 稽徵機關接到結算申報書後，應派員調查，核定其所得額及應納稅額。
    2. 前項調查，稽徵機關得視當地納稅義務人之多寡採分業抽樣調查方法，核定各該業所得額之標準。
    3. 納稅義務人申報之所得額如在前項規定標準以上，即以其原申報額為準。但如經稽徵機關發現申報異常或涉有匿報、短報或漏報所得額之情事，或申報之所得額不及前項規定標準者，得再個別調查核定之。
    4. 各業納稅義務人所得額標準之核定，應徵詢各該業同業公會之意見。
    5. 稽徵機關對所得稅案件進行書面審核、查帳審核與其他調查方式之辦法，及對影響所得額、應納稅額及稅額扣抵計算項目之查核準則，由財政部定之。

另

    稅捐稽徵法  第 五 節 退稅

    第 28 條

    1. 因適用法令、認定事實、計算或其他原因之錯誤，致溢繳稅款者，納稅義務人得自繳納之日起十年內提出具體證明，申請退還；屆期未申請者，不得再行申請。但因可歸責於政府機關之錯誤，致溢繳稅款者，其退稅請求權自繳納之日起十五年間不行使而消滅。
    2. 稅捐稽徵機關於前項規定期間內知有錯誤原因者，應自知有錯誤原因之日起二年內查明退還。
    3. 納稅義務人對核定稅捐處分不服，依法提起行政救濟，經行政法院實體判決確定者，不適用前二項規定。
    4. 第一項規定溢繳之稅款，納稅義務人以現金繳納者，應自其繳納該項稅款之日起，至填發收入退還書或國庫支票之日止，按溢繳之稅額，依各年度一月一日郵政儲金一年期定期儲金固定利率，按日加計利息，一併退還。
    5. 中華民國一百十年十一月三十日修正之本條文施行時，因修正施行前第一項事由致溢繳稅款，尚未逾五年之申請退還期間者，適用修正施行後之第一項本文規定；因修正施行前第二項事由致溢繳稅款者，應自修正施行之日起十五年內申請退還。
    6. 中華民國一百十年十一月三十日修正之本條文施行前，因修正施行前第一項或第二項事由致溢繳稅款者，於修正施行後申請退還，或於修正施行前已申請尚未退還或已退還尚未確定案件，適用第四項規定加計利息一併退還。但修正施行前之規定有利於納稅義務人者，適用修正施行前之規定。
    行為人明知無納稅義務，違反稅法或其他法律規定所繳納之款項，不得依第一項規定請求返還。


大法官#474（公務人員保險） #723（醫院、健保）

**時效**應為國會保留、應法律明訂

不得規定太短、太長


其他依所得稅法第八十條第五項規定訂定者。

營利事業所得稅查核準則

是否符合授權明確性？

【肯定説】母法整體觀察，可以推論出，對於成本收入等之計算方式，有授權之意涵。或應該將所得稅法第24條亦作爲授權依據：

    所得稅法 第 24 條 
    1. 營利事業所得之計算，以其本年度收入總額減除各項成本費用、損失及稅捐後之純益額為所得額。所得額之計算，涉有應稅所得及免稅所得者，其相關之成本、費用或損失，除可直接合理明確歸屬者，得個別歸屬認列外，應作合理之分攤；其分攤辦法，由財政部定之。
    2. 營利事業帳載應付未付之帳款、費用、損失及其他各項債務，逾請求權時效尚未給付者，應於時效消滅年度轉列其他收入，俟實際給付時，再以營業外支出列帳。
    3. 營利事業有第十四條第一項第四類利息所得中之短期票券利息所得，除依第八十八條規定扣繳稅款外，不計入營利事業所得額。但營利事業持有之短期票券發票日在中華民國九十九年一月一日以後者，其利息所得應計入營利事業所得額課稅。
    4. 自中華民國九十九年一月一日起，營利事業持有依金融資產證券化條例或不動產證券化條例規定發行之受益證券或資產基礎證券，所獲配之利息所得應計入營利事業所得額課稅，不適用金融資產證券化條例第四十一條第二項及不動產證券化條例第五十條第三項分離課稅之規定。
    5. 總機構在中華民國境外之營利事業，因投資於國內其他營利事業，所獲配之股利或盈餘，除依第八十八條規定扣繳稅款外，不計入營利事業所得額。


判斷是否居住者，一年居住183天


## 國際稅法的根本性決定

### 國際稅法的三個思考層次

 個人的公平 Individual Equity

- 避免國際間的重複課稅
- 個人及企業的成本費用應核實扣除
- 跨境交易的虧損扣除
=》**净所得**課徵原則

---
柯老師Q:重複課稅，違憲嗎？違誰的憲？（沒有國際憲法的概念啦）

所得來源地國家基於主權而課稅，
稅籍居住地國家的責任啦，（應該是要退讓的）

國際法的基本規則，域外法權：需要屬人、或屬地之鏈接（刑法、稅法）

國際租稅法


先不管國際稅，只看内國法，一些表面上不是重複課稅，但實質上形成重複課稅

土地增值稅（資本利得稅）（對於受贈人課）、贈與稅（對贈與人課）
對於一筆財產的移動，對與移動的雙方，沒有重複課稅的外觀，但具有重複課稅的實質！

營業稅、烟品健康捐、菸酒稅（屬於特種消費稅），簡直是三重課稅

比例原則，只能推出絞殺禁止。沒辦法從量能課稅原則導出那個課稅的界限！
德國聯邦憲法法院 1995年，（半數原則）不能超過半數的要件，那時是在講德國的財產稅。

德國重複課稅的例子很多
德國的營業稅是直接稅、=地方營利事業所得稅
還有聯邦稅呢

到了2006年，德國聯邦憲法法院：這個地方沒有半數原則。

美國有平等原則的違憲審查，而沒有對於比例原則的違憲審查。

總之是沒有違憲的問題！
雙重課稅之避免乃二戰後國際間之政策目標，推進國際貿易。

---
重複處罰，也是假議題

大法官 #604

不應該以一行爲、數行爲來評價，應該從行爲與結果之整體而評價其罪責相當，整體考察，給予相對應的處罰

殺人、偷300件内褲

不是綫性的關係啦！

飆車飆到一定程度就不是幾張罰單的問題了，就變成公共危險的問題了


法律系的學習，就是對於習以爲常的規則，問，爲什麽，要挑戰

很多學問道理，在本質上是一致的。

對一個行爲，國家的一次性的罪的宣泄（形容詞），在構成要件、法律效果進行重複評價？

---



 經濟上的效率 Economic Efficiency
 跨國間的公平 Interjurisdictional Equity



